/**:
  ros__parameters:
    # Camera Settings
    fps: 60
    resolution: "SVGA"  # Options: HD2K, HD1080, SVGA
    depth_mode: "NEURAL_LIGHT"  # Options: NEURAL, NEURAL_LIGHT, NEURAL_PLUS

    # Map / Area File
    area_file: "/home/nvidia/ros2_ws/src/zed_slam/data/maps/test.area"

    # Mapping Mode
    # initial_mapping: true  -> build a brand-new map
    # initial_mapping: false -> localize on (or update) an existing map
    initial_mapping: false

    # update_map: true  -> lifetime mapping (append to existing map)
    # update_map: false -> pure localization (read-only)
    update_map: false

    enable_localization_only : false